### ISSUE TITLE
How do I get msm globally

### ISSUE THREAD

**Issue by jswhisperer** [MycroftAI/mycroft-skills-manager#95]
I've followed the install instructions but msm is not found. I'm not a python developer, do I need another step?

**Comment by krisgesling** [comment]
Hi there, I'm assuming you are using this on a device that has Mycroft installed.

We use a Python virtual environment rather than installing all of Mycroft's dependencies globally. You can use this without activating the python venv by using `mycroft-msm` instead of `msm`. If the command isn't available on your system $PATH you can find it in `mycroft-core/bin/mycroft-msm`.

If you really do want to install MSM globally you can do so by running `pip install msm` from outside the python venv. I would however question the need for this, and assume it's probably not going to solve whatever problem you are facing.

**Comment by jswhisperer** [comment]
would it be beneficial to add the source step to the msm docs? As a primarily js developer I was pretty lost.
Thanks for the help
